# Generated by Django 4.1.4 on 2022-12-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydata',
            name='lock',
            field=models.FloatField(max_length=64),
        ),
        migrations.AlterField(
            model_name='querydata',
            name='rows',
            field=models.FloatField(max_length=64),
        ),
    ]
