# Generated by Django 4.1.4 on 2022-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0002_alter_querydata_lock_alter_querydata_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='domain',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='ip_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
