# Generated by Django 4.1.4 on 2022-12-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0004_querydata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querydata',
            name='status',
        ),
        migrations.AddField(
            model_name='instance',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
